### DISCUSSION TITLE
Using lower case in the headerTitle text

### DISCUSSION THREAD

**Discussion by samuelchau** [Flyer53/jsPanel4#210] [Q&A] [answered]
Does anyone know how can I make the text in the headerTitle use lower case ?
By default, it will turn all the characters in the string value to upper case (with different sizes for the upper case and lower case characters used in the original string)

**Comment by Flyer53** [comment, marked as answer]
If you look at the css file you'll find the following css rules:
```css
.jsPanel-titlebar .jsPanel-title {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  font-variant: small-caps;
  font-weight: normal;
  margin: 0 5px 0 8px;
  min-width: 0;
}
```
The one you want to change is `font-variant: small-caps;`

So just add some css to your own style sheet like...
```css
.jsPanel-titlebar .jsPanel-title {
  font-variant: normal;
}
```
...in order to overwrite the default style for all your panels.
Make sure you load your css after the jsPanel css.
