### ISSUE TITLE
Set Header height to a fixed value

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#127]
Morning... How can I set the header on all panels (globally) fixed to 60px height?

Stay SAFE

Hugo

**Comment by Flyer53** [comment]
Good morning Hugo,
To set header height to `60px` for all panels simply add the following CSS to your style sheet which you load after `jspanel.css`.
```css
.jsPanel .jsPanel-hdr {
    height: 60px;
}
```
Note that the title text and controls itself will remain at the top of the header section.

If you additionally want the title text and controls to be vertically centered within the header section use
```css
.jsPanel .jsPanel-hdr {
    height: 60px;
}
.jsPanel .jsPanel-hdr .jsPanel-headerbar {
    flex-grow: 1;
}
```
instead.

The CSS above assumes you don't have an extra header toolbar configured. 

Let me know how it works out ... and please don't wait 6 weeks, ok! 😏 

Regards,
Stefan
