### ISSUE TITLE
[Question] Removing modal background fade-in animation

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#17]
Hi Stefan,

I'm looking at http://jspanel.de/docs/#extensions/modal.

How can I create a modal so that there's no fade-in animation of the backgdrop whatsoever?

Thanks!

**Comment by Flyer53** [comment]
Hi Temuri
Just override the modal backdrop css after `jspanel.css` is loaded like
```css
.jsPanel-modal-backdrop {
    animation: '';
    animation-fill-mode: unset;
    animation-duration: unset;
    background: rgb(0,0,0);
    opacity: 0.65;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```
Adjust background-color and opacity to your needs and it should be done.
